export default {
	ARR_ITEM_SIZE: 85,
	ARR_ITEM_MARGIN: 15,
	ARR_ITEM_RADIUS: 15,
	ARR_TEXT_SIZE: 40,
	POINTER_MARGIN: 20,
	POINTER_LENGTH: 75,
	POINTER_ARROW_LENGTH: 25,
	POINTER_ARROW_WIDTH: 8,
	POINTER_TEXT_SIZE: 40,
	POINTER_TEXT_MARGIN: 40,
};
